// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/me/jiangew/snippet/hazelcast/protobuf/freeze.proto

package me.jiangew.dodekatheon.minerva.hazelcast.protobuf;

public final class FreezeProtos {
  private FreezeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FreezeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.jiangew.snippet.hazelcast.protobuf.Freeze)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string orderId = 1;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>string orderId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>double amount = 2;</code>
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code me.jiangew.snippet.hazelcast.protobuf.Freeze}
   */
  public  static final class Freeze extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.jiangew.snippet.hazelcast.protobuf.Freeze)
      FreezeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Freeze.newBuilder() to construct.
    private Freeze(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Freeze() {
      orderId_ = "";
      amount_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Freeze(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 17: {

              amount_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FreezeProtos.Freeze.class, FreezeProtos.Freeze.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderId_;
    /**
     * <code>string orderId = 1;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>string orderId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private double amount_;
    /**
     * <code>double amount = 2;</code>
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderId_);
      }
      if (amount_ != 0D) {
        output.writeDouble(2, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderId_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FreezeProtos.Freeze)) {
        return super.equals(obj);
      }
      FreezeProtos.Freeze other = (FreezeProtos.Freeze) obj;

      boolean result = true;
      result = result && getOrderId()
          .equals(other.getOrderId());
      result = result && (
          java.lang.Double.doubleToLongBits(getAmount())
          == java.lang.Double.doubleToLongBits(
              other.getAmount()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FreezeProtos.Freeze parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.Freeze parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.Freeze parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.Freeze parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.Freeze parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.Freeze parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.Freeze parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FreezeProtos.Freeze parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FreezeProtos.Freeze parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FreezeProtos.Freeze parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FreezeProtos.Freeze parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FreezeProtos.Freeze parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FreezeProtos.Freeze prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.jiangew.snippet.hazelcast.protobuf.Freeze}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.jiangew.snippet.hazelcast.protobuf.Freeze)
        FreezeProtos.FreezeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FreezeProtos.Freeze.class, FreezeProtos.Freeze.Builder.class);
      }

      // Construct using FreezeProtos.Freeze.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        orderId_ = "";

        amount_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_descriptor;
      }

      @java.lang.Override
      public FreezeProtos.Freeze getDefaultInstanceForType() {
        return FreezeProtos.Freeze.getDefaultInstance();
      }

      @java.lang.Override
      public FreezeProtos.Freeze build() {
        FreezeProtos.Freeze result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FreezeProtos.Freeze buildPartial() {
        FreezeProtos.Freeze result = new FreezeProtos.Freeze(this);
        result.orderId_ = orderId_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FreezeProtos.Freeze) {
          return mergeFrom((FreezeProtos.Freeze)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FreezeProtos.Freeze other) {
        if (other == FreezeProtos.Freeze.getDefaultInstance()) return this;
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FreezeProtos.Freeze parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FreezeProtos.Freeze) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>string orderId = 1;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>double amount = 2;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amount = 2;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.jiangew.snippet.hazelcast.protobuf.Freeze)
    }

    // @@protoc_insertion_point(class_scope:me.jiangew.snippet.hazelcast.protobuf.Freeze)
    private static final FreezeProtos.Freeze DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FreezeProtos.Freeze();
    }

    public static FreezeProtos.Freeze getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Freeze>
        PARSER = new com.google.protobuf.AbstractParser<Freeze>() {
      @java.lang.Override
      public Freeze parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Freeze(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Freeze> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Freeze> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FreezeProtos.Freeze getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubaccountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.jiangew.snippet.hazelcast.protobuf.Subaccount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string subAccountId = 1;</code>
     */
    java.lang.String getSubAccountId();
    /**
     * <code>string subAccountId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSubAccountIdBytes();

    /**
     * <code>double availableBalance = 2;</code>
     */
    double getAvailableBalance();

    /**
     * <code>string version = 3;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 3;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */
    int getFreezeCount();
    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */
    boolean containsFreeze(
        java.lang.String key);
    /**
     * Use {@link #getFreezeMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, FreezeProtos.Freeze>
    getFreeze();
    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */
    java.util.Map<java.lang.String, FreezeProtos.Freeze>
    getFreezeMap();
    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */

    FreezeProtos.Freeze getFreezeOrDefault(
        java.lang.String key,
        FreezeProtos.Freeze defaultValue);
    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */

    FreezeProtos.Freeze getFreezeOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code me.jiangew.snippet.hazelcast.protobuf.Subaccount}
   */
  public  static final class Subaccount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.jiangew.snippet.hazelcast.protobuf.Subaccount)
      SubaccountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subaccount.newBuilder() to construct.
    private Subaccount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subaccount() {
      subAccountId_ = "";
      availableBalance_ = 0D;
      version_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Subaccount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              subAccountId_ = s;
              break;
            }
            case 17: {

              availableBalance_ = input.readDouble();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                freeze_ = com.google.protobuf.MapField.newMapField(
                    FreezeDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, FreezeProtos.Freeze>
              freeze__ = input.readMessage(
                  FreezeDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              freeze_.getMutableMap().put(
                  freeze__.getKey(), freeze__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetFreeze();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FreezeProtos.Subaccount.class, FreezeProtos.Subaccount.Builder.class);
    }

    private int bitField0_;
    public static final int SUBACCOUNTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object subAccountId_;
    /**
     * <code>string subAccountId = 1;</code>
     */
    public java.lang.String getSubAccountId() {
      java.lang.Object ref = subAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>string subAccountId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSubAccountIdBytes() {
      java.lang.Object ref = subAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVAILABLEBALANCE_FIELD_NUMBER = 2;
    private double availableBalance_;
    /**
     * <code>double availableBalance = 2;</code>
     */
    public double getAvailableBalance() {
      return availableBalance_;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 3;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FREEZE_FIELD_NUMBER = 4;
    private static final class FreezeDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, FreezeProtos.Freeze> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, FreezeProtos.Freeze>newDefaultInstance(
                  FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_FreezeEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  FreezeProtos.Freeze.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, FreezeProtos.Freeze> freeze_;
    private com.google.protobuf.MapField<java.lang.String, FreezeProtos.Freeze>
    internalGetFreeze() {
      if (freeze_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FreezeDefaultEntryHolder.defaultEntry);
      }
      return freeze_;
    }

    public int getFreezeCount() {
      return internalGetFreeze().getMap().size();
    }
    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */

    public boolean containsFreeze(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFreeze().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFreezeMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, FreezeProtos.Freeze> getFreeze() {
      return getFreezeMap();
    }
    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */

    public java.util.Map<java.lang.String, FreezeProtos.Freeze> getFreezeMap() {
      return internalGetFreeze().getMap();
    }
    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */

    public FreezeProtos.Freeze getFreezeOrDefault(
        java.lang.String key,
        FreezeProtos.Freeze defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, FreezeProtos.Freeze> map =
          internalGetFreeze().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
     */

    public FreezeProtos.Freeze getFreezeOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, FreezeProtos.Freeze> map =
          internalGetFreeze().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSubAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subAccountId_);
      }
      if (availableBalance_ != 0D) {
        output.writeDouble(2, availableBalance_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetFreeze(),
          FreezeDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSubAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subAccountId_);
      }
      if (availableBalance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, availableBalance_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
      }
      for (java.util.Map.Entry<java.lang.String, FreezeProtos.Freeze> entry
           : internalGetFreeze().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, FreezeProtos.Freeze>
        freeze__ = FreezeDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, freeze__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FreezeProtos.Subaccount)) {
        return super.equals(obj);
      }
      FreezeProtos.Subaccount other = (FreezeProtos.Subaccount) obj;

      boolean result = true;
      result = result && getSubAccountId()
          .equals(other.getSubAccountId());
      result = result && (
          java.lang.Double.doubleToLongBits(getAvailableBalance())
          == java.lang.Double.doubleToLongBits(
              other.getAvailableBalance()));
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && internalGetFreeze().equals(
          other.internalGetFreeze());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBACCOUNTID_FIELD_NUMBER;
      hash = (53 * hash) + getSubAccountId().hashCode();
      hash = (37 * hash) + AVAILABLEBALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAvailableBalance()));
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      if (!internalGetFreeze().getMap().isEmpty()) {
        hash = (37 * hash) + FREEZE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetFreeze().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FreezeProtos.Subaccount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.Subaccount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.Subaccount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.Subaccount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.Subaccount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.Subaccount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.Subaccount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FreezeProtos.Subaccount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FreezeProtos.Subaccount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FreezeProtos.Subaccount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FreezeProtos.Subaccount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FreezeProtos.Subaccount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FreezeProtos.Subaccount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.jiangew.snippet.hazelcast.protobuf.Subaccount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.jiangew.snippet.hazelcast.protobuf.Subaccount)
        FreezeProtos.SubaccountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetFreeze();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableFreeze();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FreezeProtos.Subaccount.class, FreezeProtos.Subaccount.Builder.class);
      }

      // Construct using FreezeProtos.Subaccount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        subAccountId_ = "";

        availableBalance_ = 0D;

        version_ = "";

        internalGetMutableFreeze().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_descriptor;
      }

      @java.lang.Override
      public FreezeProtos.Subaccount getDefaultInstanceForType() {
        return FreezeProtos.Subaccount.getDefaultInstance();
      }

      @java.lang.Override
      public FreezeProtos.Subaccount build() {
        FreezeProtos.Subaccount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FreezeProtos.Subaccount buildPartial() {
        FreezeProtos.Subaccount result = new FreezeProtos.Subaccount(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.subAccountId_ = subAccountId_;
        result.availableBalance_ = availableBalance_;
        result.version_ = version_;
        result.freeze_ = internalGetFreeze();
        result.freeze_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FreezeProtos.Subaccount) {
          return mergeFrom((FreezeProtos.Subaccount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FreezeProtos.Subaccount other) {
        if (other == FreezeProtos.Subaccount.getDefaultInstance()) return this;
        if (!other.getSubAccountId().isEmpty()) {
          subAccountId_ = other.subAccountId_;
          onChanged();
        }
        if (other.getAvailableBalance() != 0D) {
          setAvailableBalance(other.getAvailableBalance());
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        internalGetMutableFreeze().mergeFrom(
            other.internalGetFreeze());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FreezeProtos.Subaccount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FreezeProtos.Subaccount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object subAccountId_ = "";
      /**
       * <code>string subAccountId = 1;</code>
       */
      public java.lang.String getSubAccountId() {
        java.lang.Object ref = subAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subAccountId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSubAccountIdBytes() {
        java.lang.Object ref = subAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subAccountId = 1;</code>
       */
      public Builder setSubAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subAccountId = 1;</code>
       */
      public Builder clearSubAccountId() {
        
        subAccountId_ = getDefaultInstance().getSubAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>string subAccountId = 1;</code>
       */
      public Builder setSubAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subAccountId_ = value;
        onChanged();
        return this;
      }

      private double availableBalance_ ;
      /**
       * <code>double availableBalance = 2;</code>
       */
      public double getAvailableBalance() {
        return availableBalance_;
      }
      /**
       * <code>double availableBalance = 2;</code>
       */
      public Builder setAvailableBalance(double value) {
        
        availableBalance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double availableBalance = 2;</code>
       */
      public Builder clearAvailableBalance() {
        
        availableBalance_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 3;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 3;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 3;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 3;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 3;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, FreezeProtos.Freeze> freeze_;
      private com.google.protobuf.MapField<java.lang.String, FreezeProtos.Freeze>
      internalGetFreeze() {
        if (freeze_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FreezeDefaultEntryHolder.defaultEntry);
        }
        return freeze_;
      }
      private com.google.protobuf.MapField<java.lang.String, FreezeProtos.Freeze>
      internalGetMutableFreeze() {
        onChanged();;
        if (freeze_ == null) {
          freeze_ = com.google.protobuf.MapField.newMapField(
              FreezeDefaultEntryHolder.defaultEntry);
        }
        if (!freeze_.isMutable()) {
          freeze_ = freeze_.copy();
        }
        return freeze_;
      }

      public int getFreezeCount() {
        return internalGetFreeze().getMap().size();
      }
      /**
       * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
       */

      public boolean containsFreeze(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetFreeze().getMap().containsKey(key);
      }
      /**
       * Use {@link #getFreezeMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, FreezeProtos.Freeze> getFreeze() {
        return getFreezeMap();
      }
      /**
       * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
       */

      public java.util.Map<java.lang.String, FreezeProtos.Freeze> getFreezeMap() {
        return internalGetFreeze().getMap();
      }
      /**
       * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
       */

      public FreezeProtos.Freeze getFreezeOrDefault(
          java.lang.String key,
          FreezeProtos.Freeze defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, FreezeProtos.Freeze> map =
            internalGetFreeze().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
       */

      public FreezeProtos.Freeze getFreezeOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, FreezeProtos.Freeze> map =
            internalGetFreeze().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearFreeze() {
        internalGetMutableFreeze().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
       */

      public Builder removeFreeze(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableFreeze().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, FreezeProtos.Freeze>
      getMutableFreeze() {
        return internalGetMutableFreeze().getMutableMap();
      }
      /**
       * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
       */
      public Builder putFreeze(
          java.lang.String key,
          FreezeProtos.Freeze value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableFreeze().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .me.jiangew.snippet.hazelcast.protobuf.Freeze&gt; freeze = 4;</code>
       */

      public Builder putAllFreeze(
          java.util.Map<java.lang.String, FreezeProtos.Freeze> values) {
        internalGetMutableFreeze().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.jiangew.snippet.hazelcast.protobuf.Subaccount)
    }

    // @@protoc_insertion_point(class_scope:me.jiangew.snippet.hazelcast.protobuf.Subaccount)
    private static final FreezeProtos.Subaccount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FreezeProtos.Subaccount();
    }

    public static FreezeProtos.Subaccount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subaccount>
        PARSER = new com.google.protobuf.AbstractParser<Subaccount>() {
      @java.lang.Override
      public Subaccount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Subaccount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Subaccount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subaccount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FreezeProtos.Subaccount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubaccountEntryProcessorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:me.jiangew.snippet.hazelcast.protobuf.SubaccountEntryProcessor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string orderId = 1;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>string orderId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>string subAccountId = 2;</code>
     */
    java.lang.String getSubAccountId();
    /**
     * <code>string subAccountId = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubAccountIdBytes();

    /**
     * <code>double balance = 3;</code>
     */
    double getBalance();
  }
  /**
   * Protobuf type {@code me.jiangew.snippet.hazelcast.protobuf.SubaccountEntryProcessor}
   */
  public  static final class SubaccountEntryProcessor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:me.jiangew.snippet.hazelcast.protobuf.SubaccountEntryProcessor)
      SubaccountEntryProcessorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubaccountEntryProcessor.newBuilder() to construct.
    private SubaccountEntryProcessor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubaccountEntryProcessor() {
      orderId_ = "";
      subAccountId_ = "";
      balance_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubaccountEntryProcessor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              subAccountId_ = s;
              break;
            }
            case 25: {

              balance_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FreezeProtos.SubaccountEntryProcessor.class, FreezeProtos.SubaccountEntryProcessor.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object orderId_;
    /**
     * <code>string orderId = 1;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>string orderId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBACCOUNTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object subAccountId_;
    /**
     * <code>string subAccountId = 2;</code>
     */
    public java.lang.String getSubAccountId() {
      java.lang.Object ref = subAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>string subAccountId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubAccountIdBytes() {
      java.lang.Object ref = subAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BALANCE_FIELD_NUMBER = 3;
    private double balance_;
    /**
     * <code>double balance = 3;</code>
     */
    public double getBalance() {
      return balance_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderId_);
      }
      if (!getSubAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subAccountId_);
      }
      if (balance_ != 0D) {
        output.writeDouble(3, balance_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderId_);
      }
      if (!getSubAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subAccountId_);
      }
      if (balance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, balance_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FreezeProtos.SubaccountEntryProcessor)) {
        return super.equals(obj);
      }
      FreezeProtos.SubaccountEntryProcessor other = (FreezeProtos.SubaccountEntryProcessor) obj;

      boolean result = true;
      result = result && getOrderId()
          .equals(other.getOrderId());
      result = result && getSubAccountId()
          .equals(other.getSubAccountId());
      result = result && (
          java.lang.Double.doubleToLongBits(getBalance())
          == java.lang.Double.doubleToLongBits(
              other.getBalance()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + SUBACCOUNTID_FIELD_NUMBER;
      hash = (53 * hash) + getSubAccountId().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBalance()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FreezeProtos.SubaccountEntryProcessor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FreezeProtos.SubaccountEntryProcessor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FreezeProtos.SubaccountEntryProcessor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code me.jiangew.snippet.hazelcast.protobuf.SubaccountEntryProcessor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:me.jiangew.snippet.hazelcast.protobuf.SubaccountEntryProcessor)
        FreezeProtos.SubaccountEntryProcessorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FreezeProtos.SubaccountEntryProcessor.class, FreezeProtos.SubaccountEntryProcessor.Builder.class);
      }

      // Construct using FreezeProtos.SubaccountEntryProcessor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        orderId_ = "";

        subAccountId_ = "";

        balance_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FreezeProtos.internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_descriptor;
      }

      @java.lang.Override
      public FreezeProtos.SubaccountEntryProcessor getDefaultInstanceForType() {
        return FreezeProtos.SubaccountEntryProcessor.getDefaultInstance();
      }

      @java.lang.Override
      public FreezeProtos.SubaccountEntryProcessor build() {
        FreezeProtos.SubaccountEntryProcessor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FreezeProtos.SubaccountEntryProcessor buildPartial() {
        FreezeProtos.SubaccountEntryProcessor result = new FreezeProtos.SubaccountEntryProcessor(this);
        result.orderId_ = orderId_;
        result.subAccountId_ = subAccountId_;
        result.balance_ = balance_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FreezeProtos.SubaccountEntryProcessor) {
          return mergeFrom((FreezeProtos.SubaccountEntryProcessor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FreezeProtos.SubaccountEntryProcessor other) {
        if (other == FreezeProtos.SubaccountEntryProcessor.getDefaultInstance()) return this;
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (!other.getSubAccountId().isEmpty()) {
          subAccountId_ = other.subAccountId_;
          onChanged();
        }
        if (other.getBalance() != 0D) {
          setBalance(other.getBalance());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FreezeProtos.SubaccountEntryProcessor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FreezeProtos.SubaccountEntryProcessor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>string orderId = 1;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 1;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subAccountId_ = "";
      /**
       * <code>string subAccountId = 2;</code>
       */
      public java.lang.String getSubAccountId() {
        java.lang.Object ref = subAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subAccountId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubAccountIdBytes() {
        java.lang.Object ref = subAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subAccountId = 2;</code>
       */
      public Builder setSubAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subAccountId = 2;</code>
       */
      public Builder clearSubAccountId() {
        
        subAccountId_ = getDefaultInstance().getSubAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>string subAccountId = 2;</code>
       */
      public Builder setSubAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subAccountId_ = value;
        onChanged();
        return this;
      }

      private double balance_ ;
      /**
       * <code>double balance = 3;</code>
       */
      public double getBalance() {
        return balance_;
      }
      /**
       * <code>double balance = 3;</code>
       */
      public Builder setBalance(double value) {
        
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double balance = 3;</code>
       */
      public Builder clearBalance() {
        
        balance_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:me.jiangew.snippet.hazelcast.protobuf.SubaccountEntryProcessor)
    }

    // @@protoc_insertion_point(class_scope:me.jiangew.snippet.hazelcast.protobuf.SubaccountEntryProcessor)
    private static final FreezeProtos.SubaccountEntryProcessor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FreezeProtos.SubaccountEntryProcessor();
    }

    public static FreezeProtos.SubaccountEntryProcessor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubaccountEntryProcessor>
        PARSER = new com.google.protobuf.AbstractParser<SubaccountEntryProcessor>() {
      @java.lang.Override
      public SubaccountEntryProcessor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubaccountEntryProcessor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubaccountEntryProcessor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubaccountEntryProcessor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FreezeProtos.SubaccountEntryProcessor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_FreezeEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_FreezeEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@src/main/java/me/jiangew/snippet/hazel" +
      "cast/protobuf/freeze.proto\022%me.jiangew.s" +
      "nippet.hazelcast.protobuf\")\n\006Freeze\022\017\n\007o" +
      "rderId\030\001 \001(\t\022\016\n\006amount\030\002 \001(\001\"\372\001\n\nSubacco" +
      "unt\022\024\n\014subAccountId\030\001 \001(\t\022\030\n\020availableBa" +
      "lance\030\002 \001(\001\022\017\n\007version\030\003 \001(\t\022M\n\006freeze\030\004" +
      " \003(\0132=.me.jiangew.snippet.hazelcast.prot" +
      "obuf.Subaccount.FreezeEntry\032\\\n\013FreezeEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022<\n\005value\030\002 \001(\0132-.me.jian" +
      "gew.snippet.hazelcast.protobuf.Freeze:\0028" +
      "\001\"R\n\030SubaccountEntryProcessor\022\017\n\007orderId" +
      "\030\001 \001(\t\022\024\n\014subAccountId\030\002 \001(\t\022\017\n\007balance\030" +
      "\003 \001(\001B5\n%me.jiangew.snippet.hazelcast.pr" +
      "otobufB\014FreezeProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_jiangew_snippet_hazelcast_protobuf_Freeze_descriptor,
        new java.lang.String[] { "OrderId", "Amount", });
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_descriptor,
        new java.lang.String[] { "SubAccountId", "AvailableBalance", "Version", "Freeze", });
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_FreezeEntry_descriptor =
      internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_descriptor.getNestedTypes().get(0);
    internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_FreezeEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_jiangew_snippet_hazelcast_protobuf_Subaccount_FreezeEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_jiangew_snippet_hazelcast_protobuf_SubaccountEntryProcessor_descriptor,
        new java.lang.String[] { "OrderId", "SubAccountId", "Balance", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
